#ifndef VIBEOS_SYSCALL_H
#define VIBEOS_SYSCALL_H

#include <stdint.h>

typedef enum vibeos_syscall_id {
    VIBEOS_SYSCALL_NOP = 0,
    VIBEOS_SYSCALL_EVENT_SIGNAL = 1,
    VIBEOS_SYSCALL_EVENT_CLEAR = 2,
    VIBEOS_SYSCALL_HANDLE_ALLOC = 3,
    VIBEOS_SYSCALL_HANDLE_CLOSE = 4,
    VIBEOS_SYSCALL_WAITSET_ADD_EVENT = 5,
    VIBEOS_SYSCALL_WAITSET_STATS_GET = 6,
    VIBEOS_SYSCALL_WAITSET_STATS_EXT_GET = 7,
    VIBEOS_SYSCALL_WAITSET_WAKE_POLICY_SET = 8,
    VIBEOS_SYSCALL_WAITSET_WAKE_POLICY_GET = 9,
    VIBEOS_SYSCALL_WAITSET_STATS_RESET = 18,
    VIBEOS_SYSCALL_PROCESS_SPAWN = 10,
    VIBEOS_SYSCALL_PROCESS_STATE_GET = 11,
    VIBEOS_SYSCALL_PROCESS_STATE_SET = 12,
    VIBEOS_SYSCALL_PROCESS_TERMINATE = 13,
    VIBEOS_SYSCALL_PROCESS_COUNT_GET = 14,
    VIBEOS_SYSCALL_THREAD_COUNT_GET = 15,
    VIBEOS_SYSCALL_PROCESS_LIVE_COUNT_GET = 16,
    VIBEOS_SYSCALL_PROCESS_TERMINATED_COUNT_GET = 17,
    VIBEOS_SYSCALL_PROCESS_STATE_COUNT_GET = 19,
    VIBEOS_SYSCALL_THREAD_CREATE = 20,
    VIBEOS_SYSCALL_THREAD_STATE_GET = 21,
    VIBEOS_SYSCALL_THREAD_STATE_SET = 22,
    VIBEOS_SYSCALL_THREAD_EXIT = 23,
    VIBEOS_SYSCALL_THREAD_STATE_COUNT_GET = 24,
    VIBEOS_SYSCALL_PROCESS_STATE_SUMMARY_GET = 25,
    VIBEOS_SYSCALL_THREAD_STATE_SUMMARY_GET = 26,
    VIBEOS_SYSCALL_PROC_TRANSITION_COUNTERS_GET = 27,
    VIBEOS_SYSCALL_PROC_TRANSITION_COUNTERS_RESET = 28,
    VIBEOS_SYSCALL_WAITSET_OWNER_GET = 29,
    VIBEOS_SYSCALL_VM_MAP = 30,
    VIBEOS_SYSCALL_VM_UNMAP = 31,
    VIBEOS_SYSCALL_VM_PROTECT = 32,
    VIBEOS_SYSCALL_PROC_AUDIT_COUNT = 40,
    VIBEOS_SYSCALL_PROC_AUDIT_GET = 41,
    VIBEOS_SYSCALL_PROC_AUDIT_POLICY_SET = 42,
    VIBEOS_SYSCALL_PROC_AUDIT_POLICY_GET = 43,
    VIBEOS_SYSCALL_PROC_AUDIT_DROPPED = 44,
    VIBEOS_SYSCALL_PROC_AUDIT_COUNT_ACTION = 45,
    VIBEOS_SYSCALL_PROC_AUDIT_COUNT_SUCCESS = 46,
    VIBEOS_SYSCALL_PROC_AUDIT_SUMMARY = 47,
    VIBEOS_SYSCALL_WAITSET_SNAPSHOT_GET = 48,
    VIBEOS_SYSCALL_SCHED_RUNNABLE_GET = 50,
    VIBEOS_SYSCALL_SCHED_RUNQUEUE_DEPTH_GET = 51,
    VIBEOS_SYSCALL_SCHED_CPU_COUNT_GET = 52,
    VIBEOS_SYSCALL_SCHED_PREEMPTIONS_GET = 53,
    VIBEOS_SYSCALL_SCHED_WAIT_TIMEOUTS_GET = 54,
    VIBEOS_SYSCALL_SCHED_WAIT_WAKES_GET = 55,
    VIBEOS_SYSCALL_SCHED_PREEMPTIONS_TOTAL_GET = 56,
    VIBEOS_SYSCALL_SCHED_WAIT_TIMEOUTS_TOTAL_GET = 57,
    VIBEOS_SYSCALL_SCHED_WAIT_WAKES_TOTAL_GET = 58,
    VIBEOS_SYSCALL_SCHED_COUNTER_SUMMARY_GET = 59,
    VIBEOS_SYSCALL_SCHED_COUNTERS_RESET = 60
} vibeos_syscall_id_t;

typedef struct vibeos_syscall_frame {
    uint64_t id;
    uint64_t arg0;
    uint64_t arg1;
    uint64_t arg2;
    int64_t result;
} vibeos_syscall_frame_t;

struct vibeos_kernel;

int64_t vibeos_syscall_dispatch(struct vibeos_kernel *kernel, vibeos_syscall_frame_t *frame);

#endif
