#!/usr/bin/env python3
"""The LTP tests that belong to a phase of docs/abi/phases.md, one name a line.

    scripts/dev/ltp-list.py L1 [<git revision>]        > tests/corpus/ltp-l1.txt

A phase's tests are the ones whose name starts with a syscall the registry
gave to that phase - matched as scripts/dev/corpus-report.py matches them,
longest name first, so clone301 is clone3's. The registry is read as it stood
at <revision> (default: the commit that closed Part A, before L1 began),
because a phase that is finished has no rows left under its name: its syscalls
are "done", which is what the tests are there to check.
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BEFORE_L1 = "6c4f96e"


def main():
    phase = sys.argv[1] if len(sys.argv) > 1 else "L1"
    rev = sys.argv[2] if len(sys.argv) > 2 else BEFORE_L1
    text = subprocess.run(["git", "-C", ROOT, "show", rev + ":kernel/abi/linux_syscalls.def"],
                          capture_output=True, text=True, check=True).stdout
    rows = re.findall(r"^SYSCALL\(\s*\d+,\s*(\w+),\s*(\w+),\s*(\w+),", text, re.M)
    names = sorted((n for n, _, _ in rows), key=len, reverse=True)
    wanted = {n for n, _, ph in rows if ph == phase}
    out = []
    for line in open(os.path.join(ROOT, "tests", "corpus", "ltp-built.txt"), encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        binary = line.split("/")[-1]
        if "." in binary:
            continue    # an object file the build left executable, not a test
        for n in names:
            # A whole name, not the start of a longer word: "time" is not
            # timerfd01's syscall, and took it from L4 until this said so.
            if binary.startswith(n) and not binary[len(n):len(n) + 1].isalpha():
                if n in wanted:
                    out.append(binary)
                break
        else:
            # No syscall's name starts it: LTP names some directories after a
            # family - inotify01, pselect01, timerfd01, epoll-ltp - and these
            # matched nothing, so L4's list was missing a third of its tests.
            # The family's syscalls are those whose name starts with the
            # test's stem; the test is theirs when they are all one phase's.
            # A refused row ("R": epoll_ctl_old and the like) is nobody's
            # phase, and does not make a family two phases' either.
            stem = re.match(r"[a-z]+", binary)
            phases = {ph for n2, _, ph in rows
                      if stem and n2.startswith(stem.group(0)) and ph != "R"}
            if len(phases) == 1:
                if phase in phases:
                    out.append(binary)
                continue
            # Neither: the longest name it merely starts with, as before -
            # statvfs01 is statfs's, which only "stat" reaches.
            for n in names:
                if binary.startswith(n):
                    if n in wanted:
                        out.append(binary)
                    break
    # LF whatever the host: the list is read by a shell script in the guest's
    # build environment, and a carriage return becomes part of a test's name.
    sys.stdout.reconfigure(newline="\n")
    print("# LTP tests for the syscalls phase %s of docs/abi/phases.md owned at %s." % (phase, rev))
    print("# Generated by scripts/dev/ltp-list.py; run with scripts/dev/ltp-run.sh <build> --list <this file>.")
    for t in sorted(set(out)):
        print(t)
    return 0


if __name__ == "__main__":
    sys.exit(main())
