#!/usr/bin/env python3
"""The LTP tests that belong to a phase of docs/abi/phases.md, one name a line.

    scripts/dev/ltp-list.py L1 [<git revision>]        > tests/corpus/ltp-l1.txt

A phase's tests are the ones whose name starts with a syscall the registry
gave to that phase - matched as scripts/dev/corpus-report.py matches them,
longest name first, so clone301 is clone3's. The registry is read as it stood
at <revision> (default: the commit that closed Part A, before L1 began),
because a phase that is finished has no rows left under its name: its syscalls
are "done", which is what the tests are there to check.
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BEFORE_L1 = "6c4f96e"


def main():
    phase = sys.argv[1] if len(sys.argv) > 1 else "L1"
    rev = sys.argv[2] if len(sys.argv) > 2 else BEFORE_L1
    text = subprocess.run(["git", "-C", ROOT, "show", rev + ":kernel/abi/linux_syscalls.def"],
                          capture_output=True, text=True, check=True).stdout
    rows = re.findall(r"^SYSCALL\(\s*\d+,\s*(\w+),\s*(\w+),\s*(\w+),", text, re.M)
    names = sorted((n for n, _, _ in rows), key=len, reverse=True)
    wanted = {n for n, _, ph in rows if ph == phase}
    out = []
    for line in open(os.path.join(ROOT, "tests", "corpus", "ltp-built.txt"), encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        binary = line.split("/")[-1]
        for n in names:
            if binary.startswith(n):
                if n in wanted:
                    out.append(binary)
                break
    # LF whatever the host: the list is read by a shell script in the guest's
    # build environment, and a carriage return becomes part of a test's name.
    sys.stdout.reconfigure(newline="\n")
    print("# LTP tests for the syscalls phase %s of docs/abi/phases.md owned at %s." % (phase, rev))
    print("# Generated by scripts/dev/ltp-list.py; run with scripts/dev/ltp-run.sh <build> --list <this file>.")
    for t in sorted(set(out)):
        print(t)
    return 0


if __name__ == "__main__":
    sys.exit(main())
